# Generated by Django 5.0.4 on 2024-05-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='status',
            field=models.CharField(blank=True, choices=[('Accept', 'Accept'), ('Minor', 'Minor Revisions'), ('Major', 'Major Revisions'), ('Reject', 'Reject')], max_length=100),
        ),
    ]
