# Generated by Django 5.0.4 on 2024-05-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('acronym', models.CharField(max_length=100, unique=True)),
                ('web_page', models.URLField()),
                ('submission_link', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(choices=[('AFG', 'Afghanistan'), ('ALB', 'Albania'), ('DZA', 'Algeria'), ('AND', 'Andorra'), ('AGO', 'Angola'), ('ATG', 'Antigua and Barbuda'), ('ARG', 'Argentina'), ('ARM', 'Armenia'), ('AUS', 'Australia'), ('AUT', 'Austria'), ('AZE', 'Azerbaijan'), ('BHS', 'Bahamas'), ('BHR', 'Bahrain'), ('BGD', 'Bangladesh'), ('BRB', 'Barbados'), ('BLR', 'Belarus'), ('BEL', 'Belgium'), ('BLZ', 'Belize'), ('BEN', 'Benin'), ('BTN', 'Bhutan'), ('BOL', 'Bolivia'), ('BIH', 'Bosnia and Herzegovina'), ('BWA', 'Botswana'), ('BRA', 'Brazil'), ('BRN', 'Brunei'), ('BGR', 'Bulgaria'), ('BFA', 'Burkina Faso'), ('BDI', 'Burundi'), ('CPV', 'Cabo Verde'), ('KHM', 'Cambodia'), ('CMR', 'Cameroon'), ('CAN', 'Canada'), ('CAF', 'Central African Republic'), ('TCD', 'Chad'), ('CHL', 'Chile'), ('CHN', 'China'), ('COL', 'Colombia'), ('COM', 'Comoros'), ('COG', 'Congo'), ('CRI', 'Costa Rica'), ('HRV', 'Croatia'), ('CUB', 'Cuba'), ('CYP', 'Cyprus'), ('CZE', 'Czech Republic'), ('DNK', 'Denmark'), ('DJI', 'Djibouti'), ('DMA', 'Dominica'), ('DOM', 'Dominican Republic'), ('ECU', 'Ecuador'), ('EGY', 'Egypt'), ('SLV', 'El Salvador'), ('GNQ', 'Equatorial Guinea'), ('ERI', 'Eritrea'), ('EST', 'Estonia'), ('SWZ', 'Eswatini'), ('ETH', 'Ethiopia'), ('FJI', 'Fiji'), ('FIN', 'Finland'), ('FRA', 'France'), ('GAB', 'Gabon'), ('GMB', 'Gambia'), ('GEO', 'Georgia'), ('DEU', 'Germany'), ('GHA', 'Ghana'), ('GRC', 'Greece'), ('GRD', 'Grenada'), ('GTM', 'Guatemala'), ('GIN', 'Guinea'), ('GNB', 'Guinea-Bissau'), ('GUY', 'Guyana'), ('HTI', 'Haiti'), ('HND', 'Honduras'), ('HUN', 'Hungary'), ('ISL', 'Iceland'), ('IND', 'India'), ('IDN', 'Indonesia'), ('IRN', 'Iran'), ('IRQ', 'Iraq'), ('IRL', 'Ireland'), ('ISR', 'Israel'), ('ITA', 'Italy'), ('JAM', 'Jamaica'), ('JPN', 'Japan'), ('JOR', 'Jordan'), ('KAZ', 'Kazakhstan'), ('KEN', 'Kenya'), ('KIR', 'Kiribati'), ('PRK', 'North Korea'), ('KOR', 'South Korea'), ('KWT', 'Kuwait'), ('KGZ', 'Kyrgyzstan'), ('LAO', 'Laos'), ('LVA', 'Latvia'), ('LBN', 'Lebanon'), ('LSO', 'Lesotho'), ('LBR', 'Liberia'), ('LBY', 'Libya'), ('LIE', 'Liechtenstein'), ('LTU', 'Lithuania'), ('LUX', 'Luxembourg'), ('MDG', 'Madagascar'), ('MWI', 'Malawi'), ('MYS', 'Malaysia'), ('MDV', 'Maldives'), ('MLI', 'Mali'), ('MLT', 'Malta'), ('MHL', 'Marshall Islands'), ('MRT', 'Mauritania'), ('MUS', 'Mauritius'), ('MEX', 'Mexico'), ('FSM', 'Micronesia'), ('MDA', 'Moldova'), ('MCO', 'Monaco'), ('MNG', 'Mongolia'), ('MNE', 'Montenegro'), ('MAR', 'Morocco'), ('MOZ', 'Mozambique'), ('MMR', 'Myanmar'), ('NAM', 'Namibia'), ('NRU', 'Nauru'), ('NPL', 'Nepal'), ('NLD', 'Netherlands'), ('NZL', 'New Zealand'), ('NIC', 'Nicaragua'), ('NER', 'Niger'), ('NGA', 'Nigeria'), ('MKD', 'North Macedonia'), ('NOR', 'Norway'), ('OMN', 'Oman'), ('PAK', 'Pakistan'), ('PLW', 'Palau'), ('PAN', 'Panama'), ('PNG', 'Papua New Guinea'), ('PRY', 'Paraguay'), ('PER', 'Peru'), ('PHL', 'Philippines'), ('POL', 'Poland'), ('PRT', 'Portugal'), ('QAT', 'Qatar'), ('ROU', 'Romania'), ('RUS', 'Russia'), ('RWA', 'Rwanda'), ('KNA', 'Saint Kitts and Nevis'), ('LCA', 'Saint Lucia'), ('VCT', 'Saint Vincent and the Grenadines'), ('WSM', 'Samoa'), ('SMR', 'San Marino'), ('STP', 'Sao Tome and Principe'), ('SAU', 'Saudi Arabia'), ('SEN', 'Senegal'), ('SRB', 'Serbia'), ('SYC', 'Seychelles'), ('SLE', 'Sierra Leone'), ('SGP', 'Singapore'), ('SVK', 'Slovakia'), ('SVN', 'Slovenia'), ('SLB', 'Solomon Islands'), ('SOM', 'Somalia'), ('ZAF', 'South Africa'), ('SSD', 'South Sudan'), ('ESP', 'Spain'), ('LKA', 'Sri Lanka'), ('SDN', 'Sudan'), ('SUR', 'Suriname'), ('SWE', 'Sweden'), ('CHE', 'Switzerland'), ('SYR', 'Syria'), ('TJK', 'Tajikistan'), ('TZA', 'Tanzania'), ('THA', 'Thailand'), ('TLS', 'Timor-Leste'), ('TGO', 'Togo'), ('TON', 'Tonga'), ('TTO', 'Trinidad and Tobago'), ('TUN', 'Tunisia'), ('TUR', 'Turkey'), ('TKM', 'Turkmenistan'), ('TUV', 'Tuvalu'), ('UGA', 'Uganda'), ('UKR', 'Ukraine'), ('ARE', 'United Arab Emirates'), ('GBR', 'United Kingdom'), ('USA', 'United States'), ('URY', 'Uruguay'), ('UZB', 'Uzbekistan'), ('VUT', 'Vanuatu'), ('VAT', 'Vatican City'), ('VEN', 'Venezuela'), ('VNM', 'Vietnam'), ('YEM', 'Yemen'), ('ZMB', 'Zambia'), ('ZWE', 'Zimbabwe')], max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('abstract_reg_deadline', models.DateField()),
                ('submission_deadline', models.DateField()),
                ('topic', models.CharField(choices=[('accounting_finance', 'Accounting and Finance'), ('art_humanities', 'Art and Humanities'), ('biological_sciences', 'Biological Sciences'), ('business_management', 'Business and Management'), ('chemistry', 'Chemistry'), ('civil_engineering', 'Civil Engineering'), ('computing', 'Computing'), ('earth_environmental_sciences', 'Earth and Environmental Sciences'), ('economics', 'Economics'), ('education_science', 'Education Science'), ('energy', 'Energy'), ('engineering', 'Engineering'), ('genomics_bioinformatics', 'Genomics and Bioinformatics'), ('health_sciences', 'Health Sciences'), ('language_linguistics', 'Language and Linguistics'), ('materials_science', 'Materials Science'), ('mathematics_statistics', 'Mathematics and Statistics'), ('mechanical_engineering', 'Mechanical Engineering'), ('physics', 'Physics'), ('social_sciences', 'Social Sciences'), ('technology', 'Technology')], max_length=200)),
            ],
        ),
    ]
